
export const blockedUsers = [
 {
    banId: 1234,
    name: "Ahmed Raza",
    gender: "Male",
    email: "john@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 1356,
    name: "Rabia Siddiqui",
    gender: "Female",
    email: "emily@email.com",
    phone: "+923315551234",
    city: "Lahore",
    country: "Pakistan",
    maritalStatus: "Married",
    dob: "14‑05‑1999",
    joinDate: "12 Jan 2024",
    lastLogin: "Mar 02 2023",
    profileViews: 102,
    plan: "Gold",
    notches: 233,
    verified: true,
    banReason: "Harassment",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679468",
    reportedBy: "Sara",
    reportReason: "Harassment",
    reportDate: "21 Jun 2022",
    reportDescription:
      "User repeatedly sent abusive messages to other members.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 5688,
    name: "Hamza Farooq",
    gender: "Male",
    email: "clava@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8765,
    name: "Mahmoor Javed",
    gender: "Female",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Gold",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8666,
    name: "Fahad Iqbal",
    gender: "Male",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Married",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8767,
    name: "Fatima Noor",
    gender: "Female",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8768,
    name: "Hassan Shah",
    gender: "Male",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8769,
    name: "Ayesha Khan",
    gender: "Female",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8770,
    name: "Zain UlAbideen",
    gender: "Male",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
  {
    banId: 8771,
    name: "Hina Tariq",
    gender: "Male",
    email: "soro@email.com",
    phone: "+92 300 123 4567",
    city: "Karachi",
    country: "Pakistan",
    maritalStatus: "Single",
    dob: "10‑11‑1998",
    joinDate: "12 Jan 2024",
    lastLogin: "Feb 16 2023",
    profileViews: 65,
    plan: "Free",
    notches: 122,
    verified: false,
    banReason: "Fake Profile",
    banDate: "12 Jan 2024",
    status: "Block",
    reportId: "#679467",
    reportedBy: "Majeed",
    reportReason: "Inappropriate Behavior",
    reportDate: "17 Jun 2022",
    reportDescription:
      "Profile was repeatedly created with fake photos and misleading information.",
    avatar: "/assets/blockuser.png",
  },
];