export const allUsersData = [ 
  {
    id: 1234,
    name: "Ahmed Raza",
    email: "john@gmail.com",
    joinDate: "Jan 12, 2024",
    profileReports: 3,
    reportId: "#679467",
    reportedBy: "Fatima Noor",
    reportReason: "Spamming",
    reportDescription:
      "User is sending unsolicited messages to multiple people.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 1356,
    name: "Rabia Siddiqui",
    email: "emilila@gmail.com",
    joinDate: "Feb 02, 2024",
    profileReports: 1,
    reportId: "#123456",
    reportedBy: "Hassan Shah",
    reportReason: "Inappropriate Profile Picture",
    reportDescription: "The profile picture violates community guidelines.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 5688,
    name: "Hamza Farooq",
    email: "sarah@gmail.com",
    joinDate: "Mar 20, 2024",
    profileReports: 5,
    reportId: "#789012",
    reportedBy: "Ahmed Raza",
    reportReason: "Harassment",
    reportDescription: "This user is continuously harassing me in messages.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8761,
    name: "Mahnoor Javed",
    email: "sarah@gmail.com",
    joinDate: "Jan 12, 2024",
    profileReports: 3,
    reportId: "#679468",
    reportedBy: "Ayesha Noor",
    reportReason: "Spamming",
    reportDescription:
      "User is sending unsolicited messages to multiple people.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8762,
    name: "Fahad Iqbal",
    email: "sarah@gmail.com",
    joinDate: "Feb 02, 2024",
    profileReports: 1,
    reportId: "#123454",
    reportedBy: "Shah",
    reportReason: "Inappropriate Profile Picture",
    reportDescription: "The profile picture violates community guidelines.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8763,
    name: "Fatima Noor",
    email: "sarah@gmail.com",
    joinDate: "Mar 20, 2024",
    profileReports: 5,
    reportId: "#789010",
    reportedBy: "Ahmad ",
    reportReason: "Harassment",
    reportDescription: "This user is continuously harassing me in messages.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8764,
    name: "Hassan Shah",
    email: "sarah@gmail.com",
    joinDate: "Jan 12, 2024",
    profileReports: 3,
    reportId: "#679460",
    reportedBy: "Noor",
    reportReason: "Spamming",
    reportDescription:
      "User is sending unsolicited messages to multiple people.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8765,
    name: "Ayesha Khan",
    email: "sarah@gmail.com",
    joinDate: "Feb 02, 2024",
    profileReports: 1,
    reportId: "#123446",
    reportedBy: "Ali Shah",
    reportReason: "Inappropriate Profile Picture",
    reportDescription: "The profile picture violates community guidelines.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8766,
    name: "Zain Ul Abideen",
    email: "sarah@gmail.com",
    joinDate: "Mar 20, 2024",
    profileReports: 5,
    reportId: "#789019",
    reportedBy: "Anas",
    reportReason: "Harassment",
    reportDescription: "This user is continuously harassing me in messages.",
    profilePic: "/assets/contentpic.png",
  },
  {
    id: 8767,
    name: "Hina Tariq",
    email: "sarah@gmail.com",
    joinDate: "Mar 20, 2024",
    profileReports: 5,
    reportId: "#789017",
    reportedBy: "Rana",
    reportReason: "Harassment",
    reportDescription: "This user is continuously harassing me in messages.",
    profilePic: "/assets/contentpic.png",
  },
];
